# -*- coding: utf-8 -*-
"""Character_language.txt: фамилии и имена (они же роли и клички существ)."""
import io, json, re, collections

base = u'C:/Games/The Scroll of Taiwu/The Scroll of Taiwu_Data/StreamingAssets/'
CYR = re.compile(u'[\u0400-\u04FF]')
PREF = ('Surname_', 'SurName_', 'GivenName_')

M = {
 # --- фамилии ---
 u"A'": u'А', u'Ah': u'А', u'Bai': u'Бай', u'Baili': u'Байли', u'Dawa': u'Дава',
 u'Dayue': u'Даюэ', u'Dongfang': u'Дунфан', u'Du': u'Ду', u'Duan': u'Дуань',
 u'Duanmu': u'Дуаньму', u'Dugu': u'Дугу', u'Eminent Monk': u'Преподобный',
 u'Fang': u'Фан', u'Feng': u'Фэн', u'Gongsun': u'Гунсунь', u'Guihai': u'Гуйхай',
 u'Guo': u'Го', u'He': u'Хэ', u'Hua': u'Хуа', u'Huang': u'Хуан', u'Huyan': u'Хуянь',
 u'Ji': u'Цзи', u'Jin': u'Цзинь', u'Lan': u'Лань', u'Lei': u'Лэй', u'Li': u'Ли',
 u'Liao': u'Ляо', u'Long': u'Лун', u'Lu': u'Лу', u'L\u00fc': u'Люй', u'Mei': u'Мэй',
 u'Meng': u'Мэн', u'Metal': u'Цзинь', u'Miao': u'Мяо', u'Nian': u'Нянь',
 u'Pang': u'Пан', u'Peace': u'Ань', u'Peng': u'Пэн', u'Ran': u'Жань',
 u'Red Robed': u'В красном', u'Shi': u'Ши', u'Sima': u'Сыма', u'Situ': u'Сыту',
 u'Taoist': u'Даос', u'Tian': u'Тянь', u'Wei': u'Вэй', u'Wen': u'Вэнь', u'Xi': u'Си',
 u'Xie': u'Се', u'Xu': u'Сюй', u'Xuan': u'Сюань', u'Yan': u'Янь', u'Yi': u'И',
 u'Zhang': u'Чжан', u'Zhen': u'Чжэнь', u'Zhou': u'Чжоу', u'Zhu': u'Чжу',
 u'Zhuo': u'Чжо', u'Zi': u'Цзы',

 # --- личные имена ---
 u"A'Nian": u'А-Нянь', u'Alina': u'Алина', u'Bajiu Jianyin': u'Бацзю Цзяньинь',
 u'Bingfeng': u'Бинфэн', u'Buhui': u'Бухуэй', u'Chengyan': u'Чэнъянь',
 u'Chihongzi': u'Чихунцзы', u'Chongwei': u'Чунвэй', u'Chuixing': u'Чуйсин',
 u'Dorje': u'Дордже', u'Feiming': u'Фэймин', u'Feiran': u'Фэйжань', u'Fu Xi': u'Фуси',
 u'Guiguzi': u'Гуй Гу-цзы', u'Houjiu': u'Хоуцзю', u'Hua Ju': u'Хуа Цзюй',
 u"Huang'er": u'Хуан-эр', u'Huanxin': u'Хуаньсинь', u'Huanyue': u'Хуаньюэ',
 u'Hui': u'Хуэй', u'Jianhen': u'Цзяньхэнь', u'Jieyun': u'Цзеюнь', u'Jiu Han': u'Цзю Хань',
 u'Jiuyan': u'Цзюянь', u'Kai': u'Кай', u'Kun': u'Кунь', u'Kun Wuzi': u'Кунь Уцзы',
 u'Kuiniu': u'Куйню', u'Lang': u'Лан', u'Li Zihua': u'Ли Цзыхуа', u'Lijing': u'Лицзин',
 u'Lin': u'Линь', u'Ling': u'Лин', u'Lingzhi': u'Линчжи', u'Liuli': u'Люли',
 u'Longde': u'Лундэ', u'Milu': u'Милу', u'Mingyu': u'Минъюй', u'Monu': u'Мону',
 u'Niu': u'Ню', u'Piaochen': u'Пяочэнь', u'Pu Lao': u'Пулао', u'Qi': u'Ци',
 u'Qingjun': u'Цинцзюнь', u'Qingyue': u'Цинъюэ', u'Qiu Niu': u'Цюню',
 u'Ruosheng': u'Жошэн', u'Shishufu': u'Шишуфу', u'Shuangying': u'Шуанъин',
 u'Sidao': u'Сыдао', u'Suan Ni': u'Суаньни', u'Suxia': u'Суся', u'Tianjie': u'Тяньцзе',
 u'Tianzhu': u'Тяньчжу', u'Tongsheng': u'Туншэн', u'Weizhi': u'Вэйчжи',
 u'Wufen': u'Уфэнь', u'Wuming': u'Умин', u'Wuxiao': u'Усяо', u'Wuyang': u'Уян',
 u'Wuyou': u'Ую', u'Wuzi': u'Уцзы', u'Xiaomao': u'Сяомао', u'Xindu': u'Синьду',
 u'Xuan Huangzi': u'Сюань Хуанцзы', u'Xuan Zhi': u'Сюань Чжи', u'Yaochang': u'Яочан',
 u'Yazi': u'Яцзы', u'Yi Xiang': u'И Сян', u'Yihou': u'Ихоу', u'Yin': u'Инь',
 u'Yingqi': u'Инци', u'Yingqiu': u'Инцю', u'Yitian': u'Итянь', u'You Mingzi': u'Ю Минцзы',
 u'Youxiao': u'Юсяо', u'Youyuan': u'Ююань', u'Yu': u'Юй', u'Yufu': u'Юйфу',
 u'Yuhu': u'Юйху', u"Yun'er": u'Юнь-эр', u'Yuzhuo': u'Юйчжо', u'Zhuang Qi': u'Чжуан Ци',
 u'Zhuoma': u'Чжома', u'Ba Xia': u'Бася', u'Bashe': u'Башэ', u'Bi An': u'Би Ань',
 u'Chao Feng': u'Чаофэн', u'Chi Wen': u'Чивэнь', u'Xiangshu': u'Сяншу',
 u'Master Pojin': u'Наставник Поцзинь', u'Ruler Moro': u'Владыка Моро',
 u'Lady Wuxie': u'Госпожа Усе', u'Lady Yehua': u'Госпожа Ехуа',
 u'Little Shi': u'Малыш Ши',

 # --- цзяо, луны, змеи ---
 u'Abyssal Jiao': u'Бездонный цзяо', u'Abyssal Qiu': u'Бездонный цю',
 u'Acritoxin Evil Jiao': u'Жгучий злой цзяо', u'Azure Jiao': u'Лазурный цзяо',
 u'Azure Loong': u'Лазурный лун', u'Azure Marsh Jiao': u'Цзяо лазурных топей',
 u'Black Jiao': u'Чёрный цзяо', u'Black Loong': u'Чёрный лун',
 u'Blaze Hill Jiao': u'Цзяо Пылающего холма', u'Bone-Refining Jiao': u'Костеплавильный цзяо',
 u'Burning Cloud Jiao': u'Цзяо горящих облаков', u'Cloud-Drifting Jiao': u'Облакоплывущий цзяо',
 u'Colored Jiao': u'Пёстрый цзяо', u'Crimson Loong': u'Багряный лун',
 u'Cryotoxin Evil Jiao': u'Морозный злой цзяо', u'Desolate Path Jiao': u'Цзяо пустынного пути',
 u'Devouring Jiao': u'Пожирающий цзяо', u'Ditto Jiao': u'Цзяо-подражатель',
 u'Flame Pond Jiao': u'Цзяо огненного пруда', u'Flamehorn Jiao': u'Огнерогий цзяо',
 u'Flying Thunder Jiao': u'Цзяо летучего грома', u'Golden-Eyed Jiao': u'Златоокий цзяо',
 u'Heavenly Thunder Jiao': u'Цзяо небесного грома', u'Immortal Mountain Jiao': u'Цзяо горы бессмертных',
 u'Mammon Jiao': u'Алчный цзяо', u'Mountain-Hiding Jiao': u'Цзяо, укрытый горой',
 u'Mud Pool Jiao': u'Цзяо грязевой заводи', u'Necrotoxin Evil Jiao': u'Гнилостный злой цзяо',
 u'Oneirotoxin Evil Jiao': u'Дурманный злой цзяо', u'Pyrotoxin Evil Jiao': u'Огненный злой цзяо',
 u'Qilin Jiao': u'Цзяо-цилинь', u'Red Jiao': u'Красный цзяо',
 u'Scattered-scales Jiao': u'Цзяо с осыпавшейся чешуёй', u'Sea-Disrupting Jiao': u'Море мутящий цзяо',
 u'Sea-Guarding Jiao': u'Цзяо, хранящий море', u'Thunderfire Jiao': u'Громоогненный цзяо',
 u'Umbritoxin Evil Jiao': u'Теневой злой цзяо', u'Underworld Jiao': u'Цзяо преисподней',
 u'White Jiao': u'Белый цзяо', u'White Loong': u'Белый лун', u'Yellow Jiao': u'Жёлтый цзяо',
 u'Yellow Loong': u'Жёлтый лун', u'Yin-Yang Jiao': u'Цзяо инь и ян', u'Ying Jiao': u'Ин-цзяо',
 u'Little Azure Loong': u'Лазурный лунёнок', u'Little Black Loong': u'Чёрный лунёнок',
 u'Little Crimson Loong': u'Багряный лунёнок', u'Little White Loong': u'Белый лунёнок',
 u'Little Yellow Loong': u'Жёлтый лунёнок', u'Little Black Snake': u'Чёрная змейка',
 u'Auspicious Serpent': u'Благовещий змей', u'Deep Serpent': u'Глубинный змей',
 u'Gilt Flame Serpent': u'Золочёный огненный змей',
 u'Gilt Serpent of Xuanzhou': u'Золочёный змей из Сюаньчжоу',
 u'Jiangling Water Serpent': u'Водяной змей из Цзянлина',
 u'Novemred Serpent': u'Девятикрасный змей', u'Qi Serpent': u'Змей ци',
 u'Tome Worm Serpent': u'Змей-книжный червь', u'River Python': u'Речной питон',
 u'Python': u'Питон', u'Python in the Painting': u'Питон с картины',
 u'Starry Centipede': u'Звёздная сколопендра', u'Nine-Headed Worm': u'Девятиглавый червь',
 u'Three-Eyed Xiao': u'Трёхглазый сяо', u'Drum Gu': u'Барабанный гу',

 # --- звери ---
 u'Albino Bear': u'Белый медведь', u'Brown Bear': u'Бурый медведь', u'Bison': u'Зубр',
 u'Black Boar': u'Чёрный вепрь', u'Boar': u'Вепрь', u'Eagle': u'Орёл',
 u'Golden Eagle': u'Золотой орёл', u'Aureate Lion': u'Златой лев', u'Lion': u'Лев',
 u'Lion Cub': u'Львёнок', u'Leopard': u'Барс', u'Noir Leopard': u'Чёрный барс',
 u'Tiger': u'Тигр', u'White Tiger': u'Белый тигр', u'White Bull': u'Белый бык',
 u'White Deer': u'Белый олень', u'Monkey': u'Обезьяна', u'Monkey King': u'Царь обезьян',
 u'Nimble Monkey': u'Проворная обезьяна', u'Valley Monkey': u'Долинная обезьяна',
 u'Human-faced Nimble Monkey': u'Человеколикая проворная обезьяна',
 u'Little White Ape': u'Белая обезьянка', u'White Ape of Emei Sect': u'Белая обезьяна секты Эмэй',
 u'Mountain Duck': u'Горная утка', u'Mountain Fire Turtle': u'Горная огненная черепаха',
 u'Dark Owl': u'Тёмная сова', u'Dark Pigeon': u'Тёмный голубь',
 u'Imperial Chicken': u'Государева курица', u'Rabbit Youth': u'Юный заяц',
 u'Vixen': u'Лисица', u'Inked Qilin': u'Тушевый цилинь', u'Black Widow': u'Чёрная вдова',
 u'Mind Ape': u'Обезьяна разума', u'Bloodling': u'Кровяник',

 # --- ученики, старейшины, секты ---
 u'Adept': u'Умелец', u'Apprentice': u'Ученик', u'Apprentice Herbalist': u'Ученик травника',
 u'Arahan Temple Disciple': u'Ученик храма Арахана', u'Ascended Elder': u'Вознёсшийся старейшина',
 u'Bodhi Temple Disciple': u'Ученик храма Бодхи', u'Celestial Melody Disciple': u'Ученик Небесного напева',
 u'Chief Disciple': u'Старший ученик', u'Chief Disciple with Ding': u'Старший ученик с треножником',
 u'Clan Chief': u'Глава клана', u'Commander': u'Военачальник', u'Congregant': u'Прихожанин',
 u'Eclectic School Disciple': u'Ученик смешанной школы', u'Elder': u'Старейшина',
 u'Elite': u'Отборный воин', u'Emei Exiled Disciple': u'Изгнанный ученик Эмэй',
 u'Enforcer': u'Каратель', u'Enforcer Disciple': u'Ученик-каратель',
 u'Five Immortals Exiled Disciple': u'Изгнанный ученик Пяти Бессмертных',
 u'Flying Lion Hall Disciple': u'Ученик Зала летящего льва',
 u'Fuloong Exiled Disciple': u'Изгнанный ученик Фулун',
 u'Furious Emei Disciple': u'Разгневанная ученица Эмэй',
 u'Golden Case Disciple': u'Ученик Золотого ларца', u'Honored Disciple': u'Почтенный ученик', u'Harmony Temple Disciple': u'Ученик храма Согласия',
 u'Initiate': u'Посвящаемый', u'Inner Apprentice': u'Внутренний послушник',
 u'Inner Disciple': u'Ученик Внутреннего двора', u'Jade Case Disciple': u'Ученик Яшмового ларца',
 u"Jade-Maiden Sect's Exiled Disciple": u'Изгнанная ученица секты Нефритовой Девы',
 u'Jiaology Disciple': u'Ученик-цзяовед', u'Kongsang Exiled Disciple': u'Изгнанный ученик Кунсан',
 u'Lion-Face Clan Exiled Disciple': u'Изгнанный ученик Клана Львиноликих',
 u'Mercurial Disciple': u'Переменчивый ученик', u'Misty Palace Disciple': u'Ученик Туманного дворца',
 u'Mystic Furnace Disciple': u'Ученик Тайного горна', u'Novice Disciple': u'Начинающий ученик',
 u'Outer Apprentice': u'Внешний послушник', u'Outer Disciple': u'Ученик Внешнего двора',
 u'Outsider Disciple': u'Ученик со стороны', u'Petal Case Disciple': u'Ученик Лепесткового ларца',
 u'Prajna Temple Disciple': u'Ученик храма Праджни',
 u'Rakshasa Temple Disciple': u'Ученик храма Ракшасы',
 u'Ranshan Exiled Disciple': u'Изгнанный ученик Жаньшань',
 u'Sanguine Exiled Disciple': u'Изгнанный ученик Кровавой секты',
 u'Scarlet Case Disciple': u'Ученик Багряного ларца',
 u'Sect Leader\u2019s Disciple': u'Ученик главы секты',
 u"Sect Leader's Disciple": u'Ученик главы секты',
 u'Senior': u'Старший', u'Shaolin Exiled Disciple': u'Изгнанный ученик Шаолиня',
 u'Slumbering Lion Disciple': u'Ученик Дремлющего льва',
 u'Slumbering Lion Warrior': u'Воин Дремлющего льва',
 u'Splendid Lion Disciple': u'Ученик Блистательного льва',
 u'Splendid Lion Warrior': u'Воин Блистательного льва',
 u'Steadfast Hall Disciple': u'Ученик Зала стойкости',
 u'Stone Cell Disciple': u'Ученик Каменной кельи',
 u'Successor Disciple': u'Ученик-преемник',
 u'Swordsmiths Exiled Disciple': u'Изгнанный ученик Усадьбы Ковки Мечей',
 u'Tri-School Successor': u'Преемник трёх школ',
 u'Unknown Disciple': u'Неизвестный ученик',
 u'Vajra Exiled Disciple': u'Изгнанный ученик Ваджры',
 u'Vajra Temple Disciple': u'Ученик храма Ваджры', u'Vajra Warrior': u'Воин Ваджры',
 u'Valley of Flowers Exiled Disciple': u'Изгнанная ученица Долины Сотни Цветов',
 u'Veil Disciple': u'Ученик Вуали', u'Veil Honcho': u'Заправила Вуали',
 u'Veil Scar Exiled Disciple': u'Изгнанный ученик Вуали-Шрама',
 u'Wild Lion Disciple': u'Ученик Дикого льва', u'Wild Lion Warrior': u'Воин Дикого льва',
 u'Wudang Exiled Disciple': u'Изгнанный ученик Удан',
 u'Yuanshan Exiled Disciple': u'Изгнанный ученик Юаньшань',
 u'Zhenwu Temple Disciple': u'Ученик храма Чжэньу',
 u'Retired Emei Senior': u'Отошедшая от дел старейшина Эмэй',
 u'Retired Five Immortals Senior': u'Отошедший от дел старейшина Пяти Бессмертных',
 u'Retired Fuloong Senior': u'Отошедший от дел старейшина Фулун',
 u'Retired Jade-Maiden Sect Senior': u'Отошедшая от дел старейшина секты Нефритовой Девы',
 u'Retired Kongsang Senior': u'Отошедший от дел старейшина Кунсан',
 u'Retired Lion-Face Clan Senior': u'Отошедший от дел старейшина Клана Львиноликих',
 u'Retired Ranshan Senior': u'Отошедший от дел старейшина Жаньшань',
 u'Retired Sanguine Senior': u'Отошедший от дел старейшина Кровавой секты',
 u'Retired Shaolin Senior': u'Отошедший от дел старейшина Шаолиня',
 u'Retired Swordsmiths Senior': u'Отошедший от дел старейшина Усадьбы Ковки Мечей',
 u'Retired Vajra Senior': u'Отошедший от дел старейшина Ваджры',
 u'Retired Valley of Flowers Senior': u'Отошедшая от дел старейшина Долины Сотни Цветов',
 u'Retired Veil Scar Senior': u'Отошедший от дел старейшина Вуали-Шрама',
 u'Retired Wudang Senior': u'Отошедший от дел старейшина Удан',
 u'Retired Yuanshan Elder': u'Отошедший от дел старейшина Юаньшань',
 u'Unaging Elder': u'Нестареющий старейшина', u'Venerable Elder': u'Достопочтенный старейшина',
 u'Elder Loonghead': u'Старейшина Лунтоу', u'Esteemed Recluse': u'Почитаемый отшельник',
 u'Hermit Practitioner': u'Отшельник-совершенствующийся',
 u'Deluded Hermit': u'Заблудший отшельник',

 # --- монахи и даосы ---
 u'Apathetic Central Plains Monk': u'Равнодушный монах Срединной равнины',
 u'Calm Central Plains Monk': u'Спокойный монах Срединной равнины',
 u'Confused Central Plains Monk': u'Растерянный монах Срединной равнины',
 u'Fanatic Central Plains Monk': u'Одержимый монах Срединной равнины',
 u'Hesitant Central Plains Monk': u'Нерешительный монах Срединной равнины',
 u'Polite Central Plains Monk': u'Учтивый монах Срединной равнины',
 u'Rude Central Plains Monk': u'Грубый монах Срединной равнины',
 u'Stubborn Central Plains Monk': u'Упрямый монах Срединной равнины',
 u'Suspicious Central Plains Monk': u'Подозрительный монах Срединной равнины',
 u'Uneasy Central Plains Monk': u'Встревоженный монах Срединной равнины',
 u'Western Regions Eminent Monk': u'Преподобный из Западного края',
 u'Bhikkhu': u'Бхикшу', u'Borrowed Robe Monk': u'Монах в чужой рясе',
 u'Buddhist Master': u'Буддийский наставник', u'Devout Monk': u'Благочестивый монах',
 u'Formless Monk': u'Бесформенный монах', u'Old Monk': u'Старый монах',
 u'Rogue Monk': u'Монах-отступник', u'Young Monk': u'Юный монах',
 u'Grimlord Skeleton Monk': u'Костяной монах Мрачного владыки',
 u'Manifest Buddha': u'Явленный Будда', u'Wisdom King': u'Царь мудрости',
 u'Eighteen Arhats': u'Восемнадцать архатов', u'Dharma Enforcer': u'Блюститель Дхармы',
 u'Dharma Propagator': u'Проповедник Дхармы', u'Acting Dharma King': u'Наместник царя Дхармы',
 u'Mystery Taoist': u'Загадочный даос', u'Rain Taoist': u'Даос дождя',
 u'Unkempt Taoist': u'Неопрятный даос', u'Taoist Attendant': u'Прислужник-даос',
 u'Ordained Servant': u'Посвящённый служка',

 # --- ремесленники и мирные роли ---
 u'Arcane Smith': u'Тайновед-кузнец', u'Battleforge Smith': u'Кузнец боевой ковки',
 u'Master Smith': u'Мастер-кузнец', u'Monolith Smith': u'Кузнец-исполин',
 u'Seven Stars Smith': u'Кузнец Семи звёзд', u'Verdant Smith': u'Зелёный кузнец',
 u'Little Blacksmith': u'Кузнечик-подмастерье', u'Forge Laborer': u'Работник кузни',
 u'Doctor': u'Лекарь', u'Diviner': u'Гадатель', u'Carter': u'Возчик',
 u'Armed Escort': u'Охранник обоза', u'Famed Escort': u'Прославленный охранник обоза',
 u'Embroiderer': u'Вышивальщица', u'Color Virtuoso': u'Знаток красок',
 u'Enchanted Minstrel': u'Зачарованный сказитель', u'Spellwright': u'Заклинатель',
 u'Puppet Master': u'Кукольник', u'Puppeteer': u'Кукловод',
 u'Corpse Alchemist': u'Трупный алхимик', u'Prime Alchemist': u'Главный алхимик',
 u'Revival Apothecary': u'Аптекарь воскрешения', u'Mystic Medic': u'Тайный целитель',
 u'Bone-Reviving Master': u'Наставник, оживляющий кости',
 u'Toxin Wielder': u'Владеющий ядами', u'Toxincaster': u'Ядомёт',
 u'Jadekeeper': u'Хранитель яшмы', u'Loong Keeper': u'Смотритель лунов',
 u'Deer Shepherd': u'Пастух оленей', u'Fire Keeper': u'Хранитель огня',
 u'Casket Holder': u'Держатель ларца', u'Path Guide': u'Провожатый',
 u'Patroller': u'Дозорный', u'Guard': u'Стражник', u'Servant': u'Слуга',
 u'Maid Servant': u'Служанка', u'Favored Attendant': u'Любимый прислужник',
 u'Spectral Servant': u'Призрачный слуга', u'Swordslave': u'Раб меча',
 u'Blood Scribe': u'Кровавый писец', u'Jiao Scholar': u'Цзяовед',
 u'Sanctuary Deputy': u'Помощник настоятеля', u'Midnight Market Master': u'Хозяин полуночного торга',
 u'Sick Beggar': u'Больной нищий', u'Refugee': u'Беженец', u'Islander': u'Островитянин',
 u'Granny': u'Бабушка', u'Lady': u'Госпожа', u'Madam': u'Госпожа',
 u'Girl': u'Девушка', u'Madman': u'Безумец', u'Old': u'Старец',
 u'Foster Father': u'Приёмный отец', u'Clear Sky': u'Ясное небо',

 # --- лихой люд ---
 u'Assassin': u'Убийца', u'Bandit': u'Разбойник', u'Bully': u'Задира',
 u'Cat Burglar': u'Домушник', u'Culprit': u'Виновник', u'Defiler': u'Осквернитель',
 u'Desperado': u'Отчаянный', u'Guild Bandit': u'Разбойник товарищества',
 u'Guild Bandits': u'Разбойники товарищества', u'Habitual Thief': u'Вор по привычке',
 u'Notorious Thief': u'Пресловутый вор', u'Petty Thief': u'Мелкий воришка',
 u'Mountain Raider': u'Горный налётчик', u'Outland Raider': u'Налётчик из чужих земель',
 u'Raider Leader': u'Главарь налётчиков', u'Ruffian': u'Головорез',
 u'Wandering Rogue': u'Бродячий проходимец', u'Wicked Alms Beggar': u'Злой сборщик подаяния',
 u'Wicked Associate': u'Злой подельник', u'Wicked Beggar': u'Злой нищий',
 u'Wicked Beggar Boss': u'Главарь злых нищих', u'Wicked Snake Beggar': u'Злой нищий со змеёй',
 u'Xiangshu Underling': u'Прислужник Сяншу', u'Foreign Freak': u'Чужеземный урод',
 u'Martial World Eccentric': u'Чудак вольного света', u'Heretic': u'Отступник',
 u'Uninvited Guest': u'Незваный гость', u'Exotic Fighter': u'Чужеземный боец',
 u'Evildoers': u'Злодеи', u'Kongsang Traitor': u'Отступник Кунсан',
 u'Malevolent Mystic': u'Злокозненный тайновед',

 # --- герои и странники ---
 u'Xiake': u'Странствующий воин', u'Nameless Xiake-Errant': u'Безымянный странствующий воин',
 u'Young Hero': u'Юный герой', u'Famed Hero': u'Прославленный герой',
 u'Fallen Hero': u'Павший герой', u'Greenwood Hero': u'Герой зелёных лесов',
 u'Gallant Drifter': u'Удалой скиталец', u'Dashing Beau': u'Лихой красавец',
 u'Divine Sword Wanderer': u'Странник Божественного меча',
 u'Jade Seal Wanderer': u'Странник Яшмовой печати',
 u'Yin Yang Wanderer': u'Странник инь и ян', u'Wufang Wanderer': u'Странник Уфан',
 u'Snowbrave': u'Снежный смельчак', u'Edge Dweller': u'Житель окраины',
 u'Nameless': u'Безымянный', u'Faceless': u'Безликий', u'Shadowless One': u'Бестенный',
 u'The Independent': u'Ни от кого не зависимый',

 # --- демоны, ракшасы, мары ---
 u'Blade Path Demon': u'Демон пути клинка', u'Blood Path Demon': u'Демон пути крови',
 u'Fire Path Demon': u'Демон пути огня', u'Inversion Demon': u'Демон обращения',
 u'Earthly Demon': u'Земной демон', u'Earthly Demon Follower': u'Приспешник земного демона',
 u'Heavenly Demon': u'Небесный демон', u'Heavenly Demon Follower': u'Приспешник небесного демона',
 u'Humanly Demon': u'Человечий демон', u'Humanly Demon Follower': u'Приспешник человечьего демона',
 u'Demon Queller': u'Усмиритель демонов', u'Demonic': u'Демонический',
 u'Demonic Horde': u'Демоническая орда', u'Fiend': u'Изверг', u'Flesh Fiend': u'Изверг во плоти',
 u'Bone Mara': u'Костяная Мара', u'Chaotic Mara': u'Смутная Мара',
 u'Corrupted Mara': u'Растленная Мара', u'Delusion Mara': u'Мара наваждения',
 u'Reflection Mara': u'Мара отражения', u'Serpent Mara': u'Змеиная Мара',
 u'Shattering Mara': u'Сокрушающая Мара', u'Solar Mara': u'Солнечная Мара',
 u'Tribulation Mara': u'Мара небесного испытания',
 u'Cessation Rakshasa': u'Ракшас пресечения', u'Drunk Rakshasa': u'Хмельной ракшас',
 u'Enchanting Rakshasa': u'Чарующая ракшаси', u'Finger Rakshasa': u'Перстовый ракшас',
 u'Ghostrain Rakshasa': u'Ракшас призрачного дождя',
 u'Limitless Rakshasa': u'Беспредельный ракшас', u'Myriad Rakshasa': u'Многоликий ракшас',
 u'Needle Rakshasa': u'Игольный ракшас', u'Pain Rakshasa': u'Ракшас боли',
 u'Bloody Wraith': u'Кровавый призрак', u'Sevenstar Ghost': u'Призрак Семи звёзд',
 u'Walking Corpse': u'Ходячий труп', u'Living Dead': u'Живой мертвец',
 u'Corpse Clawer': u'Трупный когтедёр', u'Soulless': u'Бездушный',
 u'Soultaker': u'Похититель душ', u'Reaper': u'Жнец', u'Resurrected One': u'Воскресший',
 u'The Enraged Soul': u'Разъярённая душа', u'The Life-Forsaken': u'Отринувший жизнь',
 u'The Tainted': u'Осквернённый', u'Three Filths': u'Три Червя',
 u'Inhuman Entity': u'Нечеловеческое существо', u'Colossal Shadow': u'Исполинская тень',
 u'Chiained Shadow': u'Скованная тень', u'Emerald Shadows': u'Изумрудные тени',
 u'Gray Shadows': u'Серые тени', u'Shadow': u'Тень',
 u'Ancient General\u2019s Remnant Soul': u'Остаток души древнего полководца',
 u"Ancient General's Remnant Soul": u'Остаток души древнего полководца',
 u"Ancient Soldier's Remnant Soul": u'Остаток души древнего воина',
 u'Bones in the Tree': u'Кости в дереве', u'Burnt Dust': u'Выжженный прах',
 u'Sinister': u'Зловещий', u'Wicked': u'Злой', u'Evil': u'Зло',
 u'Calamitous': u'Гибельный', u'Vengeful': u'Мстительный', u'Winless': u'Непобеждающий',
 u'Scattered': u'Рассеянный', u'Desireless': u'Лишённый желаний',

 # --- посланники, звания, роли сект ---
 u'Acting Valley Leader': u'Наместница главы долины',
 u'Deer-Robed Envoy': u'Посланник в оленьей рясе',
 u'Envoy of the Jade Immortal': u'Посланник Яшмового бессмертного',
 u'Five Venoms Envoy': u'Посланник Пяти ядов',
 u'Five Venoms Follower': u'Приспешник Пяти ядов',
 u'Floral Gu Follower': u'Приспешник цветочного гу',
 u'Fuloong Envoy': u'Посланник Фулун', u'Fuloong Fanatic': u'Изувер Фулун',
 u'Plumed Envoy': u'Пернатый посланник', u'Resplendent Envoy': u'Блистательный посланник',
 u'Sanguine Hou Mother Envoy': u'Посланница Кровавой матери Хоу',
 u'Sea Patrol Envoy': u'Посланник морского дозора', u'Sprite Envoy': u'Посланник духов',
 u'Qinglang Enforcer': u'Каратель Цинлан', u'Octal Path Member': u'Член Восьмеричного пути',
 u'Octal Path Successor': u'Преемник Восьмеричного пути',
 u'Mysterious One': u'Таинственный незнакомец',
 u'Mysterious One Leader': u'Глава таинственных незнакомцев',
 u'Vajra Relics Searcher': u'Искатель реликвий Ваджры',
 u'Founder of Mt. Chai': u'Основатель горы Чай',
 u'Heavenly Emperor': u'Небесный государь', u'Immortal': u'Бессмертный',
 u'Immortal Master': u'Бессмертный наставник', u'Celestial Maiden': u'Небесная дева',
 u'Divine Maiden': u'Божественная дева',
 u'Divine Maiden of True Elixir': u'Божественная дева истинного эликсира',
 u'Divine Matron': u'Божественная госпожа', u'Ice Maiden': u'Ледяная дева',
 u'Jade Belle': u'Яшмовая красавица', u'Silken Maiden': u'Шелковая дева',
 u'Enchantress': u'Чаровница', u'Temptress': u'Соблазнительница',
 u'Western Damsel': u'Дева с запада', u'Candle Immortal': u'Свечной бессмертный',
 u'Lord Blackclad': u'Господин в чёрном', u'Lord of Black Mountain': u'Владыка Чёрной горы',
 u'Black Robed One': u'Некто в чёрном', u'Grimlord': u'Мрачный владыка',
 u'Worldshaper': u'Творец мира', u'Mort Warrior': u'Воин смерти',
 u'Evil Sunderer': u'Разрыватель зла', u'Beyond the Dome': u'За пределом небосвода',
 u'Tomb Remains': u'Останки из гробницы', u'Unnamed Wounded One': u'Безымянный раненый',
 u'Echo of Taiwu': u'Отзвук Тайу', u'Seventy-Seventh': u'Семьдесят седьмой',
 u'Trinity - Earth': u'Триада - Земля', u'Trinity - Heaven': u'Триада - Небо',
 u'Trinity - Human': u'Триада - Человек',
 u'People of Wanqu': u'Народ Ваньцюй', u'Oxback Caravan': u'Караван Оксбэк',
 u"Gongshu's Caravan": u'Караван Гуншу', u'Yangtze Merchant League': u'Янцзыйский торговый союз',
 u'Pavilion of Wonders': u'Павильон чудес', u'Vault of Volumes': u'Книгохранилище',
 u'Champion\u2019s Armaments': u'Оружие поборника',
 u"Champion's Armaments": u'Оружие поборника',

 # --- манекены и механизмы ---
 u'Bamboo Dart Dummy': u'Болван с бамбуковым дротиком',
 u'Bamboo Palm Dummy': u'Болван с бамбуковой ладонью',
 u'Bamboo Staff Dummy': u'Болван с бамбуковым посохом',
 u'Wooden Dummy': u'Деревянный болван',
 u'Old Wooden Dummy': u'Старый деревянный болван',
 u'Wooden Dummy for Practice': u'Деревянный болван для отработки',
 u'Lava Mechanism A': u'Лавовый механизм А', u'Lava Mechanism B': u'Лавовый механизм Б',
 u'Lava Mechanism C': u'Лавовый механизм В',
 u"Bronze Statue of Kua'e": u'Бронзовое изваяние Куа-э',
 u"Liao's Ancient Ding": u'Древний треножник рода Ляо',
 u'Moon Treasure Mirror': u'Драгоценное зеркало луны',
 u'Star Treasure Mirror': u'Драгоценное зеркало звёзд',
 u'Sun Treasure Mirror': u'Драгоценное зеркало солнца',
 u'Fuyu Hilt': u'Рукоять Фуюй', u'Froststeel': u'Мёрзлая сталь',
 u'Sacred Wood': u'Священное дерево', u'Green Node': u'Зелёный узел',
 u'Night Glow Illusion': u'Морок ночного свечения',

 # --- отвлечённые имена ---
 u'Benevolence': u'Добросердечие', u'True Benevolence': u'Истинное добросердечие',
 u'Malevolence': u'Злонравие', u'True Malevolence': u'Истинное злонравие',
 u'Bead': u'Бусина', u'Pill': u'Пилюля', u'Clumsy': u'Неловкий',
 u'Unassuming': u'Неприметный', u'Sheathed Danger': u'Скрытая угроза',
 u'Mystic Armor': u'Тайный доспех', u'Cloud Armor': u'Облачный доспех',
 u'Unbirth': u'Нерождение', u'Rebirth': u'Перерождение',
 u'Radiant Blaze': u'Лучезарное пламя', u'Scarlet Sorrow': u'Багряная скорбь',
 u'Self-Discipline': u'Самообуздание', u'Ordeal': u'Испытание',
 u'Red Mane': u'Рыжая грива', u'Scarlet Tassel': u'Багряная кисть',
 u'Jade': u'Яшма', u'Mis-collect': u'Ошибка сбора', u'Ornate Weave': u'Узорная ткань',
 u'Jade Cicada': u'Яшмовая цикада', u'Lotus Birth': u'Рождение лотоса',
 u'Lotus Flower': u'Цветок лотоса', u'Silken Life': u'Шелковая жизнь',
 u'Solar Flame': u'Солнечное пламя', u'Vermilion Sunblaze': u'Киноварный солнечный жар',
 u'Violet Essence': u'Лиловая суть', u'Violet-Gold': u'Лилово-золотой',
 u'Verdant Blade': u'Зелёный клинок', u'The Blood Maple': u'Кровавый клён',
 u'Soul': u'Душа', u'Cloudwatch': u'Облакозор', u'Flame Patron': u'Покровитель пламени',
}

E = io.open(base + 'Language_EN/Character_language.txt', encoding='utf-8').read().split('\n')
R = io.open(base + 'Language_RU/Character_language.txt', encoding='utf-8').read().split('\n')

d = collections.OrderedDict()
miss = collections.Counter()
for i in range(0, len(E) - 1, 2):
    k = E[i]
    if not k.startswith(PREF) or CYR.search(R[i + 1]):
        continue
    en = E[i + 1].strip()
    if not en:
        continue
    if en in M:
        d[k] = M[en]
    else:
        miss[en] += 1

io.open('bchar2.json', 'w', encoding='utf-8').write(
    json.dumps({u'Character_language.txt': d}, ensure_ascii=False, indent=1))
print('переведено:', len(d), '| без пары:', sum(miss.values()), 'уникальных:', len(miss))
for k, v in sorted(miss.items()):
    print('   %3d  %s' % (v, k))
